name: Checks
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  configs_check:
    name: Validate configs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true

      - name: Run ESLint
        run: yarn eslint .

      - name: Validate marketplace config schema
        run: yarn validate:marketplace

      - name: Validate marketplace security reports schema
        run: yarn validate:marketplace-security-reports

      - name: Validate featured networks config schema
        run: yarn validate:featured-networks

      - name: Validate footer links config schema
        run: yarn validate:footer-links
